services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  evolution_api:
    image: atendai/evolution-api:v2.2.0
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${API_KEY}
      - CONSOLE_ENABLED=true
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      - DELAY_MESSAGES=true
      - BROWSER_CLIENT=Evolution API
      - BROWSER_NAME=Chrome
      - BROWSER_VERSION=10.0.0
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  postgres_data:
  evolution_instances:
  evolution_store: